## Задание на повторение материала

**1)**
Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [1]:
import numpy as np
a = np.arange(12, 24)
print(f'размер = {a.size}\nсодержимое = {a}')

размер = 12
содержимое = [12 13 14 15 16 17 18 19 20 21 22 23]


**2)**
Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [2]:
array_list = np.array([a.reshape(3, 4), a.reshape(4, 3), a.reshape(2, 6), a.reshape(6, 2), a.reshape(12, 1)], dtype=object)
for x, y in enumerate(array_list):
    print(f'{x+1})\n {y}\nразмер: {y.shape}\n')

1)
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
размер: (3, 4)

2)
 [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
размер: (4, 3)

3)
 [[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
размер: (2, 6)

4)
 [[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
размер: (6, 2)

5)
 [[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]
размер: (12, 1)



**3)**
Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [3]:
array_list = np.array([a.reshape(1, -1), a.reshape(2, -1), a.reshape(3, -1), a.reshape(-1, 2), a.reshape(-1, 3)], dtype=object)
for x, y in enumerate(array_list):
    print(f'{x+1})\n {y}\nразмер: {y.shape}\n')

1)
 [[12 13 14 15 16 17 18 19 20 21 22 23]]
размер: (1, 12)

2)
 [[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
размер: (2, 6)

3)
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
размер: (3, 4)

4)
 [[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
размер: (6, 2)

5)
 [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
размер: (4, 3)



**4)**
Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

*неа*

**5)**
Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [4]:
m = np.random.randn(3, 4)
m2 = m.flatten()

print(f'm\n{m}\n\nm2\n{m2}\n\nих размеры (size) = {m.size == m2.size}')

m
[[ 0.34962849 -0.07955758 -0.54687948 -1.17268936]
 [-0.15595509 -0.62237814  0.2624936   0.30129242]
 [-0.36582945  2.41807578  0.88201435 -0.84210217]]

m2
[ 0.34962849 -0.07955758 -0.54687948 -1.17268936 -0.15595509 -0.62237814
  0.2624936   0.30129242 -0.36582945  2.41807578  0.88201435 -0.84210217]

их размеры (size) = True


**6)**
Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [5]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

**7)**
Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [6]:
b = np.arange(20, 0, -2).reshape(1, -1)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

*разница между массивами a и b*

*a - одномерный массив*

*b - двумерный массив с одной строкой*

*если делать оба одномерными, то разницы, само собой, не будет никакой*

**8)**
Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [7]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
v = np.vstack((a, b))

print(f'a\n{a}\n\nb\n{b}\n\nv\n{v}\nразмер v = {v.size}')

a
[[0. 0.]
 [0. 0.]]

b
[[1. 1.]
 [1. 1.]
 [1. 1.]]

v
[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
размер v = 10


**9)**
Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [8]:
a = np.arange(0, 12)
A = a.reshape(4, 3)
At = A.T
B = np.dot(A, At)
np.linalg.det(B)

print(f'массив a\n{a}\n\nматрица A\n{A}\n\nматрица At - транспонированная A\n{At}\n\nA.shape[1] == At.shape[0]\
\n{A.shape[1] == At.shape[0]}\n\nматрица B\n{B}\nеё размер\n{B.shape}\n\nВычислить обратную матрицу \
для B никак нельзя, т.к. определитель матрицы B = 0\nnp.linalg.det(B)\n{np.linalg.det(B)}')

массив a
[ 0  1  2  3  4  5  6  7  8  9 10 11]

матрица A
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

матрица At - транспонированная A
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]

A.shape[1] == At.shape[0]
True

матрица B
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
её размер
(4, 4)

Вычислить обратную матрицу для B никак нельзя, т.к. определитель матрицы B = 0
np.linalg.det(B)
0.0


**10)**
Инициализируйте генератор случайных чисел с помощью объекта seed, равного 42.

In [9]:
a = np.random.randint(1, 50, 10)
np.random.seed(42)
a

array([21, 38, 11,  2, 16, 37, 44, 49, 44, 38])

**11)**
Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.

In [10]:
c = np.linspace(0, 15, 16, dtype=int)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

**12)**
Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [11]:
C = c.reshape(-1, 4)
# C.shape[1] == C.shape[0]
B
D = B + C*10
D_inv = np.linalg.inv(D)

print(f'матрица C\n{C}\n\nC.shape[1] == C.shape[0] = {C.shape[1] == C.shape[0]}\n\nматрица B\n{B}\n\nматрица D\n{D}\n\n\
определитель D = {np.linalg.det(D)}\nранг D = {np.linalg.matrix_rank(D)}\n\nобратная матрица D_inv\n{D_inv}')

матрица C
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

C.shape[1] == C.shape[0] = True

матрица B
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]

матрица D
[[  5  24  43  62]
 [ 54 100 146 192]
 [103 176 249 322]
 [152 252 352 452]]

определитель D = 5.18953807259442e-26
ранг D = 2

обратная матрица D_inv
[[ 4.66062690e+13 -1.49229688e+13 -1.09972869e+14  7.82895692e+13]
 [ 1.63480451e+14 -3.81454387e+14  2.72467419e+14 -5.44934838e+13]
 [-4.66779710e+14  8.07677680e+14 -2.15016230e+14 -1.25881740e+14]
 [ 2.56692989e+14 -4.11300324e+14  5.25216801e+13  1.02085655e+14]]


**13)**
Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [12]:
numb_one = D_inv > 0
numb_zero = D_inv < 0
D_inv[numb_one] = 1
D_inv[numb_zero] = 0

E = np.where(D_inv, B, C)

print(f'преобразовали матрицу D_inv\n{D_inv}\n\nматрица E\n{E}\n\n\nдля проверки:\nматрица С\n{C}\nматрица B\n{B}')

преобразовали матрицу D_inv
[[1. 0. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 1. 1.]]

матрица E
[[  5   1   2  32]
 [ 14   5  86   7]
 [  8  86  10  11]
 [ 32  13 212 302]]


для проверки:
матрица С
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
матрица B
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
